dist: trusty
sudo: true
language: c++

addons:
  ssh_known_hosts:
    - gitlab.fi.muni.cz
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
      - ggcov

notifications:
  email:
    - martin.jonas@mail.muni.cz

before_install:
  - eval "${SET_GCC}"
  - sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-7 90
  - pip install --user cpp-coveralls

install:
  - export CXX=g++-7
  - export CC=gcc-7
  - wget https://github.com/Z3Prover/z3/releases/download/z3-4.6.0/z3-4.6.0-x64-ubuntu-14.04.zip
  - unzip -q z3-4.6.0-x64-ubuntu-14.04.zip -d z3_downloaded
  - sudo cp z3_downloaded/z3-4.6.0-x64-ubuntu-14.04/bin/libz3.{a,so} /usr/lib/
  - sudo cp z3_downloaded/z3-4.6.0-x64-ubuntu-14.04/include/* /usr/include/
  - git clone https://github.com/utwente-fmt/sylvan.git
  - cd sylvan
  - mkdir build && cd build
  - cmake .. -DBUILD_STATIC_LIBS=ON -DBUILD_SHARED_LIBS=OFF && make -j8 && sudo make install
  - cd ..
  - rm -rf build

script:
  - mkdir build && cd build && cmake .. -DCOVERAGE=1
  - make -j4
  - make test
  - cd ..

after_success:
  - coveralls --exclude app --exclude cudd --exclude z3_downloaded --exclude tests --gcov-options '\-lp'